Repository ManoellyBernardo/helpr-front-jfs5, pull requests merged in 2022-12, with the labels that each got.

#9 Criação de página para visualizar a relação de cargos
  src/app/app-routing.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/cargo.ts
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/cargos/cargos.component.css
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
Labels: enhancement

#13 Estilização da cor primaria
  src/custom-theme.scss
Labels: enhancement

#16 Criação da página de cadastro de novos cargos.
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/cargos/cargos.module.ts
  src/app/views/cargos/new-cargo/new-cargo.component.css
  src/app/views/cargos/new-cargo/new-cargo.component.html
  src/app/views/cargos/new-cargo/new-cargo.component.ts
Labels: enhancement

#26 Exclusão de cargo
  src/app/services/cargo.service.ts
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
Labels: enhancement

#28 Alteração dos title ddas paginas
  src/app/app-routing.module.ts
  src/app/views/cargos/cargos-routing.module.ts
  src/app/views/chamados/chamados-routing.module.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/funcionarios/funcionarios-routing.module.ts
  src/app/views/home/home-routing.module.ts
  src/app/views/login/login-routing.module.ts
Labels: enhancement

#30 Adicionando dark thema
  angular.json
  src/app/app.module.ts
  src/app/components/nav-bar/nav-bar.component.css
  src/app/components/nav-bar/nav-bar.component.html
  src/app/components/nav-bar/nav-bar.component.ts
  src/custom-theme.scss
Labels: enhancement

#31 Pagina FAQ criada
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/nav-bar/nav-bar.component.html
  src/app/views/paginafaq/paginafaq.component.css
  src/app/views/paginafaq/paginafaq.component.html
  src/app/views/paginafaq/paginafaq.component.ts
  src/index.html
  src/styles.css
Labels: enhancement

#33 Criação da pagina de visualização de futuros candidatos
  src/app/components/nav-bar/nav-bar.component.html
  src/app/models/futuroCandidato.ts
  src/app/services/futuroCandidato.service.ts
  src/app/views/clientes/clientes-routing.module.ts
  src/app/views/clientes/clientes.module.ts
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.css
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.html
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.ts
Labels: enhancement

#39 Atualização do mecanismo de notificação
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/services/auth.service.ts
  src/app/services/cargo.service.ts
  src/app/services/chamado.service.ts
  src/app/services/cliente.service.ts
  src/app/services/funcionario.service.ts
  src/app/services/toastr.service.ts
  src/app/views/cargos/new-cargo/new-cargo.component.ts
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
  src/app/views/chamados/new-chamado/new-chamado.component.ts
  src/app/views/clientes/clientes/clientes.component.ts
  src/app/views/clientes/edit-cliente/edit-cliente.component.ts
  src/app/views/clientes/new-cliente/new-cliente.component.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
  src/app/views/login/login/login.component.ts
Labels: enhancement

#41 Atualização de notificações.
  src/app/services/cargo.service.ts
  src/app/services/futuroCandidato.service.ts
  src/app/views/cargos/cargos/cargos.component.ts
  src/app/views/cargos/edit-cargo/edit-cargo.component.ts
  src/app/views/clientes/futuro-candidatos/futuro-candidatos.component.ts
Labels: enhancement

#42 Criação do enum de status
  src/app/models/chamado.ts
  src/app/shared/material/enum/status.enum.ts
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
  src/app/views/chamados/edit-chamado/edit-chamado.component.ts
Labels: enhancement

#46 spinner implementado na página relação-chamados para melhor navegação do usuário
  src/app/app.component.ts
  src/app/shared/material/material.module.ts
  src/app/views/chamados/chamados.module.ts
  src/app/views/chamados/chamados/chamados.component.css
  src/app/views/chamados/chamados/chamados.component.html
  src/app/views/chamados/chamados/chamados.component.ts
Labels: enhancement

#48 Criação de rotas privadas
  src/app/app-routing.module.ts
Labels: bug, enhancement

#51 reparos
  src/app/app-routing.module.ts
  src/app/guards/permisao-acesso.guard.ts
  src/app/models/token-acess.ts
Labels: enhancement

#54 feat: implementação do spinner no funcionario
  src/app/views/funcionarios/funcionarios.module.ts
  src/app/views/funcionarios/funcionarios/funcionarios.component.css
  src/app/views/funcionarios/funcionarios/funcionarios.component.html
  src/app/views/funcionarios/funcionarios/funcionarios.component.ts
Labels: enhancement

#55 implementa o spinner em cargos
  src/app/views/cargos/cargos/cargos.component.css
  src/app/views/cargos/cargos/cargos.component.html
  src/app/views/cargos/cargos/cargos.component.ts
Labels: enhancement

#56 implementação do spinner no cliente
  src/app/views/clientes/clientes/clientes.component.css
  src/app/views/clientes/clientes/clientes.component.html
  src/app/views/clientes/clientes/clientes.component.ts
Labels: enhancement

#61 removendo guard
  src/app/app-routing.module.ts
  src/app/guards/permisao-acesso.guard.ts
Labels: bug
